stages:
- test
- deploy
- integration

qa:
  stage: test
  image: yourlabs/python
  script: flake8

pytest:
  stage: test
  image: yourlabs/python
  script:
  - pip install -e .
  - py.test -v

pypi:
  stage: deploy
  image: yourlabs/python
  script:
  - pip install -e .
  - shyml twine | bash -eux

integration:
  stage: deploy
  image: yourlabs/python
  script:
  - pip uninstall shyml
  - pip install -U shyml
  - shyml | grep twine  # default job should be there
