qa:
  stage: test
  image: yourlabs/python
  script: flake8

setup:
  stage: test
  image: yourlabs/python
  script:
  # try the generated tarball
  - rm -rf dist && python setup.py sdist && pip install dist/*
  - ./sh.yml test

pypi:
  stage: deploy
  image: yourlabs/python
  except: [tags]
  script: pypi-release
  only: [master]
  # this is in paid gitlab only
  # trigger: oss/containers
