qa:
  stage: test
  image: yourlabs/python
  script: flake8

setup:
  stage: test
  image: yourlabs/python
  script:
  - pip uninstall --yes shyml
  - virtualenv testenv && source testenv/bin/activate
  - python setup.py sdist
  - cd dist && pip install *
  - which shyml

pypi:
  stage: deploy
  image: yourlabs/python
  except: [tags]
  script: pypi-release
  # this is in paid gitlab only
  # trigger: oss/containers
