qa:
  stage: test
  image: yourlabs/python
  script: flake8

pytest:
  stage: test
  image: yourlabs/python
  script:
  - pip install -e .
  - py.test -v

setup:
  stage: test
  image: yourlabs/python
  script:
  - pip uninstall --yes shyml
  - virtualenv testenv && source testenv/bin/activate
  - python setup.py sdist
  - cd dist && pip install *
  - which shyml
  - shyml
  - shyml | grep twine

pypi:
  stage: deploy
  image: yourlabs/python
  except: [tags]
  script:
  - pip install -e .
  - shyml twine | bash -eux
