qa:
  stage: test
  image: yourlabs/python
  script: flake8

test:
  stage: test
  image: yourlabs/python
  script: py.test -v --cov

pypi:
  stage: deploy
  only:
  - /^\d+\./
  image: yourlabs/python:autoplay
  script:
  - autoplay run twine
